# Generated by Django 3.1.3 on 2020-11-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201130_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote',
        ),
    ]
